# Importing and merging

In [ ]:
import numpy as np
import pandas as pd
import sklearn as sk

In [ ]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
county_data = pd.read_csv("/content/drive/MyDrive/county-data/county_statistics.csv")
county_data.drop("Unnamed: 0",axis=1,inplace=True)
county_data

                          county state  ...  FamilyWork  Unemployment
0                      Abbeville    SC  ...         0.1           9.4
1                         Acadia    LA  ...         0.3           8.9
2                       Accomack    VA  ...         0.2           5.4
3                            Ada    ID  ...         0.1           4.3
4                          Adair    IA  ...         0.5           3.0
...                          ...   ...  ...         ...           ...
4862  Valdez-Cordova Census Area    AK  ...         0.7           7.5
4863   Wrangell City and Borough    AK  ...         2.6           7.0
4864    Yakutat City and Borough    AK  ...         0.0           6.5
4865   Yukon-Koyukuk Census Area    AK  ...         0.0          19.7
4866                    Doña Ana    NM  ...         0.1           9.3

[4867 rows x 50 columns]

In [ ]:
nyt_counties = pd.read_csv("/content/drive/MyDrive/covid-19-data-master/us-counties.csv")
nyt_counties = nyt_counties.groupby(by=['state','county','fips']).size().reset_index().drop(0, axis=1)
#nyt_counties['fips'] = nyt_counties['fips'].apply(lambda x: str(int(x)).zfill(5))
nyt_counties

        state      county     fips
0     Alabama     Autauga   1001.0
1     Alabama     Baldwin   1003.0
2     Alabama     Barbour   1005.0
3     Alabama        Bibb   1007.0
4     Alabama      Blount   1009.0
...       ...         ...      ...
3213  Wyoming  Sweetwater  56037.0
3214  Wyoming       Teton  56039.0
3215  Wyoming       Uinta  56041.0
3216  Wyoming    Washakie  56043.0
3217  Wyoming      Weston  56045.0

[3218 rows x 3 columns]

In [ ]:
mask_use = pd.read_csv("/content/drive/MyDrive/covid-19-data-master/mask-use/mask-use-by-county.csv")
#mask_use['COUNTYFP'] = mask_use['COUNTYFP'].apply(lambda x: str(int(x)).zfill(5))
mask_use.set_index('COUNTYFP', inplace=True)
mask_use

          NEVER  RARELY  SOMETIMES  FREQUENTLY  ALWAYS
COUNTYFP
1001      0.053   0.074      0.134       0.295   0.444
1003      0.083   0.059      0.098       0.323   0.436
1005      0.067   0.121      0.120       0.201   0.491
1007      0.020   0.034      0.096       0.278   0.572
1009      0.053   0.114      0.180       0.194   0.459
...         ...     ...        ...         ...     ...
56037     0.061   0.295      0.230       0.146   0.268
56039     0.095   0.157      0.160       0.247   0.340
56041     0.098   0.278      0.154       0.207   0.264
56043     0.204   0.155      0.069       0.285   0.287
56045     0.142   0.129      0.148       0.207   0.374

[3142 rows x 5 columns]

In [ ]:
state_abbrev = pd.read_csv("/content/drive/MyDrive/state_abbreviations.csv")
state_abbrev.drop('Abbrev', axis=1, inplace=True)
state_abbrev.columns = ['state', 'code']
state_abbrev

                   state code
0                Alabama   AL
1                 Alaska   AK
2                Arizona   AZ
3               Arkansas   AR
4             California   CA
5               Colorado   CO
6            Connecticut   CT
7               Delaware   DE
8   District of Columbia   DC
9                Florida   FL
10               Georgia   GA
11                Hawaii   HI
12                 Idaho   ID
13              Illinois   IL
14               Indiana   IN
15                  Iowa   IA
16                Kansas   KS
17              Kentucky   KY
18             Louisiana   LA
19                 Maine   ME
20              Maryland   MD
21         Massachusetts   MA
22              Michigan   MI
23             Minnesota   MN
24           Mississippi   MS
25              Missouri   MO
26               Montana   MT
27              Nebraska   NE
28                Nevada   NV
29         New Hampshire   NH
30            New Jersey   NJ
31            New Mexico   NM
32              New York   NY
33        North Carolina   NC
34          North Dakota   ND
35                  Ohio   OH
36              Oklahoma   OK
37                Oregon   OR
38          Pennsylvania   PA
39          Rhode Island   RI
40        South Carolina   SC
41          South Dakota   SD
42             Tennessee   TN
43                 Texas   TX
44                  Utah   UT
45               Vermont   VT
46              Virginia   VA
47            Washington   WA
48         West Virginia   WV
49             Wisconsin   WI
50               Wyoming   WY

In [ ]:
state_county_fips = nyt_counties.join(state_abbrev.set_index('state'),on='state',lsuffix="_left")
state_county_fips.drop('state',axis=1,inplace=True)
state_county_fips.columns=['county','fips','state']
state_county_fips

          county     fips state
0        Autauga   1001.0    AL
1        Baldwin   1003.0    AL
2        Barbour   1005.0    AL
3           Bibb   1007.0    AL
4         Blount   1009.0    AL
...          ...      ...   ...
3213  Sweetwater  56037.0    WY
3214       Teton  56039.0    WY
3215       Uinta  56041.0    WY
3216    Washakie  56043.0    WY
3217      Weston  56045.0    WY

[3218 rows x 3 columns]

In [ ]:
county_data_merged = state_county_fips.merge(county_data,left_on=['county','state'],right_on=['county','state'])
county_data_merged.set_index('fips',inplace=True)

county_data_merged.drop(['county','state'],axis=1,inplace=True)
county_data_merged.drop(['cases','deaths'],axis=1,inplace=True)
county_data_merged.drop('VotingAgeCitizen',axis=1,inplace=True)
county_data_merged.drop(['total_votes16','votes16_Donald_Trump','votes16_Hillary_Clinton','total_votes20','votes20_Donald_Trump', 'votes20_Joe_Biden'],axis=1,inplace=True)
#county_data_merged.drop(['Drive','Carpool','Transit','Walk','OtherTransp','WorkAtHome','MeanCommute'],axis=1,inplace=True)
#county_data_merged.drop(['Employed','PrivateWork','PublicWork','SelfEmployed','FamilyWork','Professional','Service','Office','Construction','Production'],axis=1,inplace=True)

county_data_merged

         percentage16_Donald_Trump  ...  Unemployment
fips                                ...
1001.0                       0.734  ...           5.2
1003.0                       0.774  ...           5.5
1005.0                       0.523  ...          12.4
1007.0                       0.770  ...           8.2
1009.0                       0.899  ...           4.9
...                            ...  ...           ...
56037.0                      0.729  ...           5.2
56039.0                      0.322  ...           1.3
56041.0                      0.764  ...           6.4
56043.0                      0.784  ...           6.1
56045.0                      0.869  ...           2.2

[3134 rows x 39 columns]

In [ ]:
county_data_merged.dropna(inplace=True)
mask_use = mask_use.loc[county_data_merged.index]
county_data_merged

         percentage16_Donald_Trump  ...  Unemployment
fips                                ...
1001.0                       0.734  ...           5.2
1003.0                       0.774  ...           5.5
1005.0                       0.523  ...          12.4
1007.0                       0.770  ...           8.2
1009.0                       0.899  ...           4.9
...                            ...  ...           ...
56037.0                      0.729  ...           5.2
56039.0                      0.322  ...           1.3
56041.0                      0.764  ...           6.4
56043.0                      0.784  ...           6.1
56045.0                      0.869  ...           2.2

[3041 rows x 39 columns]

In [ ]:
county_data_merged['DemMargin20'] = county_data_merged['percentage20_Joe_Biden'] - county_data_merged['percentage20_Donald_Trump']
county_data_merged['DemMargin16'] = county_data_merged['percentage16_Hillary_Clinton'] - county_data_merged['percentage16_Donald_Trump']
county_data_merged['MarginShift'] = county_data_merged['DemMargin20'] - county_data_merged['DemMargin16']
county_data_merged.drop(['percentage20_Joe_Biden', 'percentage20_Donald_Trump', 'percentage16_Donald_Trump', 'percentage16_Hillary_Clinton'], axis=1, inplace=True) 

county_data_merged['PctMale'] = county_data_merged['Men'] / county_data_merged['TotalPop']
county_data_merged['PctFemale'] = county_data_merged['Women'] / county_data_merged['TotalPop']
county_data_merged['GenderBiasMale'] = county_data_merged['PctMale'] - county_data_merged['PctFemale']
county_merged_copy = county_data_merged.copy()
county_data_merged.drop(['Men','Women', 'PctMale', 'PctFemale'],axis=1,inplace=True)

county_data_merged['lat'] = county_data_merged['lat'] / county_data_merged['lat'].mean() - 1
county_data_merged['long'] = county_data_merged['long'] / county_data_merged['long'].mean() - 1
county_data_merged

              lat      long  TotalPop  ...  DemMargin16  MarginShift  GenderBiasMale
fips                                   ...
1001.0  -0.148804 -0.059170   55036.0  ...       -0.494        0.049       -0.022494
1003.0  -0.196198 -0.047464  203360.0  ...       -0.578        0.039       -0.021174
1005.0  -0.166363 -0.072818   26201.0  ...       -0.056       -0.024        0.066830
1007.0  -0.136852 -0.053946   22580.0  ...       -0.556       -0.021        0.085120
1009.0  -0.111068 -0.059997   57667.0  ...       -0.814        0.014       -0.011913
...           ...       ...       ...  ...          ...          ...             ...
56037.0  0.089762  0.182311   44527.0  ...       -0.535        0.028        0.032228
56039.0  0.149294  0.200839   22923.0  ...        0.279        0.096        0.061728
56041.0  0.080041  0.200388   20758.0  ...       -0.615       -0.013        0.020619
56043.0  0.148491  0.169252    8253.0  ...       -0.641       -0.006       -0.002060
56045.0  0.146793  0.135453    7117.0  ...       -0.781        0.006        0.055501

[3041 rows x 37 columns]

In [ ]:
mask_use_single = mask_use.dot([0, 0.25, 0.5, 0.75, 1])
mask_use_single

fips
1001.0     0.75075
1003.0     0.74200
1005.0     0.73200
1007.0     0.83700
1009.0     0.72300
            ...
56037.0    0.56625
56039.0    0.64450
56041.0    0.56575
56043.0    0.57400
56045.0    0.63550
Length: 3041, dtype: float64

# Exploratory analysis

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(county_data_merged)

scaled_df = county_data_merged.copy()
scaled_df_index = scaled_df.index
scaled_df_columns = scaled_df.columns

scaled_df = pd.DataFrame(scaler.transform(scaled_df))
scaled_df.index = scaled_df_index
scaled_df.columns = scaled_df_columns

scaled_df[['lat','long']] = county_data_merged[['lat', 'long']]

scaled_df

              lat      long  TotalPop  ...  DemMargin16  MarginShift  GenderBiasMale
fips                                   ...
1001.0  -0.148804 -0.059170 -0.138119  ...    -0.549112     0.822422       -0.509922
1003.0  -0.196198 -0.047464  0.320017  ...    -0.830307     0.659709       -0.482158
1005.0  -0.166363 -0.072818 -0.227183  ...     0.917119    -0.365385        1.368729
1007.0  -0.136852 -0.053946 -0.238368  ...    -0.756661    -0.316571        1.753404
1009.0  -0.111068 -0.059997 -0.129993  ...    -1.620331     0.252925       -0.287380
...           ...       ...       ...  ...          ...          ...             ...
56037.0  0.089762  0.182311 -0.170579  ...    -0.686362     0.480724        0.640986
56039.0  0.149294  0.200839 -0.237308  ...     2.038551     1.587174        1.261443
56041.0  0.080041  0.200388 -0.243996  ...    -0.954166    -0.186401        0.396825
56043.0  0.148491  0.169252 -0.282620  ...    -1.041203    -0.072501       -0.080145
56045.0  0.146793  0.135453 -0.286129  ...    -1.509861     0.122755        1.130467

[3041 rows x 37 columns]

In [ ]:
corr_df = scaled_df.join(mask_use)

corr_df = corr_df.corr()
corr_df = corr_df.drop(scaled_df.columns).drop(mask_use.columns, axis=1)
corr_df

                 lat      long  ...  MarginShift  GenderBiasMale
NEVER       0.190247  0.113574  ...    -0.152985        0.026716
RARELY      0.240245  0.163475  ...    -0.135018        0.050328
SOMETIMES   0.096427  0.023900  ...    -0.170241        0.048083
FREQUENTLY  0.151288  0.081855  ...     0.030273        0.063819
ALWAYS     -0.261029 -0.146935  ...     0.161628       -0.073363

[5 rows x 37 columns]

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression().fit(scaled_df,mask_use)
df = pd.DataFrame(lr.coef_)
df.columns = scaled_df.columns
df.index = mask_use.columns

for x in df.index:
    print(df.loc[x].sort_values(ascending=False,key=abs).head(10))
    print()

lat             0.086787
Production      0.041607
Professional    0.041408
Construction    0.027030
long            0.026357
Service         0.023137
Office          0.019347
PrivateWork    -0.018251
PublicWork     -0.017943
Drive          -0.017092
Name: NEVER, dtype: float64

Professional    0.233299
Production      0.212952
Construction    0.147719
Service         0.131401
Office          0.107858
lat             0.075587
long            0.074348
PrivateWork    -0.063526
PublicWork     -0.054304
SelfEmployed   -0.033233
Name: RARELY, dtype: float64

Drive           0.113481
PrivateWork    -0.111547
PublicWork     -0.091114
WorkAtHome      0.056144
SelfEmployed   -0.056101
Production      0.052535
Carpool         0.050257
Professional    0.048812
Walk            0.046284
Transit         0.040396
Name: SOMETIMES, dtype: float64

PrivateWork     0.147932
PublicWork      0.113016
Drive          -0.078509
SelfEmployed    0.073011
long            0.068496
TotalPop       -0.039338
Employed        0.038346
WorkAtHome     -0.037666
Carpool        -0.035103
Walk           -0.034011
Name: FREQUENTLY, dtype: float64

Professional   -0.313081
Production     -0.295437
Construction   -0.197516
long           -0.197079
Service        -0.172874
lat            -0.167646
Office         -0.142540
Employed       -0.083319
TotalPop        0.083161
Hispanic        0.062030
Name: ALWAYS, dtype: float64

# Model

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(svd_solver='full')
pca.fit(scaled_df)
pca_df = pd.DataFrame(pca.transform(scaled_df))
pca_df

            0         1         2   ...        34        35            36
0     0.430570  0.713170 -1.075494  ... -0.000614  0.000034 -3.478632e-16
1     1.527404  0.749580 -1.846822  ... -0.000140  0.000436 -1.118612e-16
2    -3.858645  3.184073  1.062866  ...  0.000070  0.000141 -7.345149e-17
3    -2.398340  0.325830 -1.339382  ... -0.000525  0.000568 -1.416860e-16
4    -0.936152  0.391880 -3.582405  ... -0.000630  0.010226  1.621186e-17
...        ...       ...       ...  ...       ...       ...           ...
3036  0.683115 -0.902282 -0.688162  ...  0.000093 -0.000958  1.538939e-16
3037  5.743000 -1.960893  2.816250  ...  0.000965 -0.000384 -6.072389e-16
3038 -0.816944 -1.858238  0.143530  ...  0.009706  0.000467 -7.556167e-17
3039 -0.363982 -2.499657  0.205697  ...  0.009483 -0.008986 -1.170129e-16
3040  1.179155 -3.403594  0.844282  ...  0.000563  0.001524 -6.340482e-17

[3041 rows x 37 columns]

In [ ]:
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split

X_train_pca, X_test_pca, y_train_pca, y_test_pca = train_test_split(pca_df, mask_use, random_state=1)
pca_model = MLPRegressor(hidden_layer_sizes=(512,512,512,512)).fit(X_train_pca,y_train_pca)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(scaled_df, mask_use, random_state=1)
non_pca_model = MLPRegressor(hidden_layer_sizes=(512,512,512,512)).fit(X_train,y_train)

In [ ]:
test_predictions = pd.DataFrame(pca_model.predict(X_test_pca))
test_predictions.columns = y_test.columns
test_predictions.index = y_test.index
test_predictions - y_test_pca

            NEVER    RARELY  SOMETIMES  FREQUENTLY    ALWAYS
fips
1013.0   0.008146  0.052272  -0.131480    0.038947  0.025995
24019.0 -0.006803  0.034203   0.088105    0.025887 -0.158796
37057.0  0.031835  0.002420  -0.046482    0.059939 -0.037208
42073.0  0.040244  0.011354   0.037402   -0.089575  0.015380
19137.0 -0.125178  0.064861   0.044276   -0.144306  0.183900
...           ...       ...        ...         ...       ...
54039.0 -0.106232 -0.000204   0.074705    0.068968 -0.031436
56025.0  0.060922  0.084784   0.069383   -0.067121 -0.159362
8051.0  -0.024861  0.022346   0.043110   -0.134638  0.113940
21131.0 -0.012971 -0.019867  -0.069929   -0.079803  0.163375
29103.0  0.090151  0.029416  -0.026689   -0.086053  0.022547

[761 rows x 5 columns]

In [ ]:
test_predictions = pd.DataFrame(non_pca_model.predict(X_test))
test_predictions.columns = y_test.columns
test_predictions.index = y_test.index
test_predictions - y_test

            NEVER    RARELY  SOMETIMES  FREQUENTLY    ALWAYS
fips
1013.0   0.005048  0.028701  -0.133068    0.054298  0.048656
24019.0 -0.020128  0.048845   0.121186    0.056364 -0.267179
37057.0  0.019352  0.001652  -0.049909    0.082367 -0.059858
42073.0 -0.002357 -0.015942  -0.007656   -0.117288  0.138593
19137.0 -0.140386  0.027533   0.028901   -0.195853  0.288841
...           ...       ...        ...         ...       ...
54039.0 -0.077628  0.036013   0.070986    0.104638 -0.113055
56025.0  0.041321  0.072282   0.082595   -0.062606 -0.104170
8051.0  -0.033638 -0.028963   0.072431   -0.073761  0.055732
21131.0  0.023496 -0.015262   0.014593   -0.028281  0.015373
29103.0  0.049256  0.011141  -0.033723   -0.107577  0.075496

[761 rows x 5 columns]

In [ ]:
print(pca_model.score(X_test_pca,y_test_pca))
print(non_pca_model.score(X_test,y_test))

0.3504424927386331
0.3778644495642696

# Pipeline

In [ ]:
from sklearn.pipeline import make_pipeline 
from sklearn.model_selection import cross_val_score

X_train, X_test, y_train, y_test = train_test_split(county_data_merged, mask_use, random_state=1) 
pipeline = make_pipeline(StandardScaler(), 
                         PCA(n_components=.92,svd_solver='full'), 
                         MLPRegressor(hidden_layer_sizes=(512,512,512,512))) 
cv_errs = cross_val_score(pipeline, X=X_train, y=y_train, scoring="explained_variance", cv=5) 
cv_errs.mean()

0.2830033086455036

In [ ]:
pipeline = make_pipeline(StandardScaler(), 
                         #PCA(n_components=.92,svd_solver='full'), 
                         MLPRegressor(hidden_layer_sizes=(512,512,512,512))) 
cv_errs = cross_val_score(pipeline, X=X_train, y=y_train, scoring="explained_variance", cv=5) 
cv_errs.mean()

0.30569744275982635

# Random Forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor
X_train, X_test, y_train, y_test = train_test_split(scaled_df, mask_use, random_state=1) 
rfr = RandomForestRegressor().fit(X_train,y_train)
cv_errs = cross_val_score(RandomForestRegressor(), X=X_train, y=y_train, scoring="neg_mean_squared_error", cv=5) 
cv_errs.mean()

-0.003062363014929824

In [ ]:
cv_errs = cross_val_score(RandomForestRegressor(), X=X_train, y=y_train, scoring="r2", cv=5) 
cv_errs.mean()

0.43434189618437785

In [ ]:
rfr.score(X_test,y_test)

0.5737947089970976

In [ ]:
from sklearn.linear_model import LinearRegression
cv_errs = cross_val_score(LinearRegression(), X=X_train, y=y_train, scoring="r2", cv=5) 
cv_errs.mean()

0.29678020303685687

In [ ]:
rfr_importance_df = pd.DataFrame(rfr.feature_importances_)
rfr_importance_df.columns = ['importance']
rfr_importance_df['column'] = scaled_df.columns
rfr_importance_df.sort_values('importance',ascending=False).head(10)

    importance        column
1     0.214584          long
33    0.192965   DemMargin20
0     0.120482           lat
3     0.058929      Hispanic
19    0.026567    Production
26    0.024011   MeanCommute
32    0.018615  Unemployment
35    0.018242   MarginShift
9     0.015666        Income
11    0.015609  IncomePerCap

In [ ]:
from sklearn.inspection import permutation_importance
perm = permutation_importance(rfr,X_test,y_test)
rfr_importance_df = pd.DataFrame(perm['importances_mean'])
rfr_importance_df = pd.DataFrame(rfr.feature_importances_)
rfr_importance_df.columns = ['importance']
rfr_importance_df['column'] = scaled_df.columns
rfr_importance_df.sort_values('importance',ascending=False).head(10)

    importance        column
1     0.214584          long
33    0.192965   DemMargin20
0     0.120482           lat
3     0.058929      Hispanic
19    0.026567    Production
26    0.024011   MeanCommute
32    0.018615  Unemployment
35    0.018242   MarginShift
9     0.015666        Income
11    0.015609  IncomePerCap

In [ ]:
from sklearn.ensemble import ExtraTreesRegressor
cv_errs = cross_val_score(ExtraTreesRegressor(n_estimators=200,n_jobs=-1), X=X_train, y=y_train, scoring="explained_variance", cv=5) 
cv_errs.mean()

0.4466349216129837

In [ ]:
etr = ExtraTreesRegressor(n_estimators=200,n_jobs=-1).fit(X_train,y_train)
etr_importance_df = pd.DataFrame(etr.feature_importances_)
etr_importance_df.columns = ['importance']
etr_importance_df['column'] = scaled_df.columns
etr_importance_df.sort_values('importance',ascending=False).head(10)

    importance        column
1     0.153802          long
33    0.102878   DemMargin20
0     0.091119           lat
34    0.078420   DemMargin16
3     0.047454      Hispanic
4     0.039238         White
26    0.035178   MeanCommute
19    0.028861    Production
32    0.024997  Unemployment
6     0.021169        Native

In [ ]:
from sklearn.inspection import permutation_importance
perm = permutation_importance(etr,X_test,y_test)
etr_importance_df = pd.DataFrame(perm['importances_mean'])
etr_importance_df.columns = ['importance']
etr_importance_df['column'] = scaled_df.columns
etr_importance_df.sort_values('importance',ascending=False).head(10)

    importance        column
1     0.258778          long
0     0.153802           lat
33    0.075806   DemMargin20
3     0.039887      Hispanic
34    0.038404   DemMargin16
26    0.022832   MeanCommute
4     0.020234         White
32    0.011038  Unemployment
19    0.009176    Production
35    0.006543   MarginShift

In [ ]:
import re
for est in rfr.estimators_:
  tree_text = sk.tree.export_text(est)
  for i in range(len(scaled_df.columns)):
      tree_text = re.sub('feature_' + str(i) + " ", scaled_df.columns[i] + " ", tree_text)
 
  print(tree_text.split('\n')[3])

|   |   |   |--- DemMargin20 <= -0.37
|   |   |   |--- MarginShift <= 0.59
|   |   |   |--- MarginShift <= 0.24
|   |   |   |--- MarginShift <= 0.59
|   |   |   |--- PublicWork <= 0.35
|   |   |   |--- Production <= 0.08
|   |   |   |--- lat <= 0.09
|   |   |   |--- lat <= -0.03
|   |   |   |--- Office <= -1.18
|   |   |   |--- Production <= -0.98
|   |   |   |--- long <= -0.17
|   |   |   |--- lat <= -0.04
|   |   |   |--- lat <= 0.08
|   |   |   |--- Income <= 0.12
|   |   |   |--- IncomePerCap <= 0.31
|   |   |   |--- MarginShift <= 0.27
|   |   |   |--- MeanCommute <= -0.40
|   |   |   |--- MeanCommute <= 2.09
|   |   |   |--- ChildPoverty <= -0.65
|   |   |   |--- DemMargin20 <= 0.23
|   |   |   |--- DemMargin20 <= -0.27
|   |   |   |--- OtherTransp <= -0.50
|   |   |   |--- Transit <= 13.67
|   |   |   |--- Carpool <= -0.11
|   |   |   |--- DemMargin20 <= -0.40
|   |   |   |--- Production <= -1.41
|   |   |   |--- WorkAtHome <= 0.14
|   |   |   |--- Income <= -0.15
|   |   |   |--- long <= 0.05
|   |   |   |--- DemMargin20 <= -0.71
|   |   |   |--- MarginShift <= 0.59
|   |   |   |--- lat <= -0.01
|   |   |   |--- Poverty <= -0.95
|   |   |   |--- Production <= -0.42
|   |   |   |--- MarginShift <= -0.28
|   |   |   |--- FamilyWork <= 0.25
|   |   |   |--- Office <= -0.54
|   |   |   |--- MarginShift <= 0.55
|   |   |   |--- Income <= 0.20
|   |   |   |--- Income <= 0.20
|   |   |   |--- lat <= 0.08
|   |   |   |--- Service <= 0.85
|   |   |   |--- Transit <= -0.17
|   |   |   |--- DemMargin16 <= 0.39
|   |   |   |--- Production <= -0.34
|   |   |   |--- long <= 0.05
|   |   |   |--- DemMargin16 <= -0.14
|   |   |   |--- Income <= 0.12
|   |   |   |--- SelfEmployed <= 0.40
|   |   |   |--- lat <= -0.03
|   |   |   |--- Income <= 0.12
|   |   |   |--- long <= -0.18
|   |   |   |--- IncomeErr <= 0.52
|   |   |   |--- long <= -0.18
|   |   |   |--- long <= -0.19
|   |   |   |--- long <= -0.18
|   |   |   |--- DemMargin20 <= -0.22
|   |   |   |--- lat <= -0.03
|   |   |   |--- long <= -0.15
|   |   |   |--- IncomePerCap <= -0.27
|   |   |   |--- Walk <= -0.08
|   |   |   |--- SelfEmployed <= 0.56
|   |   |   |--- lat <= -0.06
|   |   |   |--- Service <= -0.28
|   |   |   |--- IncomePerCap <= 0.51
|   |   |   |--- DemMargin16 <= -0.38
|   |   |   |--- IncomePerCapErr <= -0.35
|   |   |   |--- Income <= 0.13
|   |   |   |--- lat <= -0.04
|   |   |   |--- long <= 0.05
|   |   |   |--- Unemployment <= 1.34
|   |   |   |--- Unemployment <= -0.73
|   |   |   |--- long <= -0.18
|   |   |   |--- OtherTransp <= 0.12
|   |   |   |--- Office <= -1.08
|   |   |   |--- MeanCommute <= 2.13
|   |   |   |--- MarginShift <= 0.27
|   |   |   |--- long <= -0.17
|   |   |   |--- Income <= -0.12
|   |   |   |--- White <= 0.15
|   |   |   |--- MarginShift <= 0.42
|   |   |   |--- Poverty <= 0.34
|   |   |   |--- MarginShift <= 0.27
|   |   |   |--- long <= -0.17
|   |   |   |--- DemMargin20 <= -0.49
|   |   |   |--- MarginShift <= 0.19
|   |   |   |--- lat <= 0.07
|   |   |   |--- Unemployment <= 0.74
|   |   |   |--- Income <= 1.17
|   |   |   |--- Office <= 1.84
|   |   |   |--- Production <= -0.81
|   |   |   |--- IncomePerCapErr <= 0.62
|   |   |   |--- IncomeErr <= -0.13
|   |   |   |--- lat <= 0.07
|   |   |   |--- Service <= 0.41
|   |   |   |--- MarginShift <= 0.34
|   |   |   |--- Native <= -0.19
|   |   |   |--- IncomeErr <= 0.09
|   |   |   |--- lat <= -0.28
|   |   |   |--- Income <= -0.18

In [ ]:
tree_text = sk.tree.export_text(rfr.estimators_[40])
for i in range(len(scaled_df.columns)):
    tree_text = re.sub('feature_' + str(i) + " ", scaled_df.columns[i] + " ", tree_text)
print(*tree_text.split('\n')[:10],sep='\n')

|--- long <= -0.13
|   |--- Transit <= -0.12
|   |   |--- DemMargin20 <= -0.28
|   |   |   |--- lat <= 0.08
|   |   |   |   |--- Poverty <= 0.27
|   |   |   |   |   |--- Service <= -0.31
|   |   |   |   |   |   |--- IncomePerCapErr <= -0.35
|   |   |   |   |   |   |   |--- PrivateWork <= 0.87
|   |   |   |   |   |   |   |   |--- FamilyWork <= -0.19
|   |   |   |   |   |   |   |   |   |--- value: [0.07, 0.10, 0.07, 0.19, 0.57]

In [ ]:

gbr = GradientBoostingRegressor().fit(scaled_df,mask_use_single)
cv_errs = -cross_val_score(GradientBoostingRegressor(), X=scaled_df, y=mask_use_single, scoring="neg_mean_squared_error", cv=5) 
cv_errs.mean()

NameError: ignored

In [ ]:
error_series = gbr.predict(scaled_df) - mask_use_single
error_series.name = "Error"
error_series = error_series.reset_index()
error_series

In [ ]:
counties = alt.topo_feature(data.us_10m.url, 'counties')

alt.Chart(counties).mark_geoshape(  
    stroke='black',
    strokeWidth=0.05
).project(
  type='albersUsa'
).transform_lookup(
    lookup='id',
    from_=alt.LookupData(error_series,'fips',['Error'])
).encode(
    color=alt.Color('Error:Q',scale=alt.Scale(scheme='redblue'),title="Error")
)

# Visualizations

In [ ]:
import altair as alt
from vega_datasets import data

In [ ]:
vis_data = mask_use.merge(county_merged_copy, left_index = True, right_index= True)
vis_data

In [ ]:
alt.Chart(vis_data).mark_circle(size=60).encode(
    x='ALWAYS',
    y='IncomePerCap'
)

In [ ]:
alt.Chart(vis_data).mark_circle(size=60).encode(
    x='NEVER',
    y='IncomePerCap'
)

In [ ]:
alt.Chart(vis_data).mark_circle(size=60).encode(
    x='ALWAYS',
    y='DemMargin20'
)

In [ ]:
alt.Chart(vis_data).mark_circle(size=60).encode(
    x='ALWAYS',
    y='PctMale'
)

In [ ]:
alt.Chart(vis_data).mark_circle(size=60).encode(
    x='NEVER',
    y='PctMale'
)

In [ ]:
alt.Chart(vis_data).mark_circle(size=60).encode(
    x='NEVER',
    y='DemMargin20'
)

In [ ]:
alt.Chart(vis_data).mark_circle(size=60).encode(
    x='ALWAYS',
    y='MeanCommute'
)

In [ ]:
import seaborn as sn
import matplotlib.pyplot as plt

plt.figure(figsize=(15,8))
sn.heatmap(corr_df.sort_values('ALWAYS',axis=1,ascending=False), cmap="YlGnBu") #, annot=True)
plt.savefig('heatmap.png')

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(scaled_df, mask_use, test_size=1/3,random_state=1)
etr = ExtraTreesRegressor(n_estimators=200,n_jobs=-1).fit(X_train,y_train)
full_predict = pd.DataFrame(etr.predict(scaled_df))
full_predict.columns = mask_use.columns
full_predict.index = mask_use.index
full_predict

In [ ]:
error_df =  full_predict - mask_use
error_df.reset_index(inplace=True)
error_df

In [ ]:
MSE = (error_df**2).drop('fips',axis=1).mean().sort_values(ascending=False)
print(MSE)
print()
print(1/(MSE/MSE['ALWAYS']))

In [ ]:
MSE**.5

In [ ]:
import altair as alt
alt.data_transformers.enable('default', max_rows=None)
alt.Chart(error_df.drop('fips',axis=1).melt()).mark_boxplot().encode(
    alt.X('variable', title="Mask Use Frequency"),
    alt.Y('value', title="Average Error By county")
).properties(
    title = 'AverageError',
    width = 400,
    height = 400
)

In [ ]:
counties = alt.topo_feature(data.us_10m.url, 'counties')
plots = []
for var in error_df.columns[:0:-1]:
    plots.append(
        alt.Chart(counties).mark_geoshape(  
            stroke='black',
            strokeWidth=0.05
        ).project(
          type='albersUsa'
        ).transform_lookup(
            lookup='id',
            from_=alt.LookupData(error_df,'fips',[var])
        ).encode(
            color=alt.Color(var+':Q',scale=alt.Scale(scheme='redblue'),title="Error")
        ).properties(
            title=var
        )
    )
alt.hconcat(*plots)

In [ ]:
error_corrs = pd.DataFrame()
for var in error_df.columns[1:]:
    high_error_counties = error_df[[var,'fips']].sort_values(var,ascending=False, key=abs).head(50)
    high_error_counties = state_county_fips.merge(high_error_counties)
    high_error_counties = high_error_counties.merge(county_data_merged.reset_index()).set_index(['state', 'county']).drop('fips',axis=1)
    error_corr = high_error_counties.corr()
    error_corr = error_corr.drop(error_corr.columns[1:], axis=1).iloc[1:]
    error_corrs[var] = error_corr[var]
for var in error_corrs.columns:
    print(error_corrs[var].sort_values(ascending=False,key=abs).head(10),end='\n\n')

In [ ]:
error_melt = error_df.melt(id_vars='fips',var_name='column',value_name='Error').merge(state_county_fips).sort_values('Error',ascending=False,key=abs).set_index(['state','county','fips'])
error_melt.head(50)

In [ ]:
lookup = error_melt.reset_index().tail(10)
lookup

In [ ]:
print(full_predict.loc[12086.0])
print()
print(mask_use.loc[12086.0])

In [ ]:
print(full_predict.loc[32009.0])
print()
print(mask_use.loc[32009.0])

In [ ]:
error_sums = abs(error_melt['Error'])
error_sums = error_sums.groupby(['state','county','fips']).sum().sort_values(ascending=False)
error_sums.head(10)

In [ ]:
error_sums.tail(10)

In [ ]:
counts = pd.Series(np.zeros(len(scaled_df_columns)))
counts.index = scaled_df_columns
for county in error_sums.reset_index()['fips'].loc[:50]:
  z_scores = scaled_df.loc[county].sort_values(ascending=False,key=abs)
  z_scores = z_scores.loc[abs(z_scores) >= 2]
  for col in z_scores.index:
      counts.loc[col] += 1
print(counts.loc[counts > 2].sort_values(ascending=False))

In [ ]:
always_error = error_df.set_index('fips')['ALWAYS']
always_error

In [ ]:
cv_errs = -cross_val_score(RandomForestRegressor(), X=scaled_df, y=always_error, scoring="explained_variance", cv=5) 
cv_errs.mean()

In [ ]:
for var in error_df.columns[1:]:
    error = error_df[var]
    rfr_error = RandomForestRegressor().fit(scaled_df, error)
    rfr_importance_df = pd.DataFrame(rfr_error.feature_importances_)
    rfr_importance_df.columns = ['importance_' + var]
    rfr_importance_df['column'] = scaled_df.columns
    rfr_importance_df.sort_values('importance_' + var,ascending=False,inplace=True)
    print(rfr_importance_df.head())
    print()

In [ ]:
rfr_error = RandomForestRegressor().fit(scaled_df, error_df)
rfr_importance_df = pd.DataFrame(rfr_error.feature_importances_)
rfr_importance_df.columns = ['importance_OVERALL']
rfr_importance_df['column'] = scaled_df.columns
rfr_importance_df.sort_values('importance_OVERALL',ascending=False,inplace=True)
print(rfr_importance_df)